version: "3.8"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev
    container_name: keycloak_local
    ports:
      - "7001:8080"
    restart: unless-stopped
    networks:
      docker-static-network:
        ipv4_address: 192.168.1.210
    environment:
      KC_DB: postgres
      KC_DB_URL_DATABASE: keycloak_db
      #Host name/ip address where the postgres is hosted
      KC_DB_URL_HOST: 192.168.1.212
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: 1234
      KEYCLOAK_USER: user
      KEYCLOAK_PASSWORD: 1234
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: 1234

networks:
  docker-static-network:
    external: true
